handbook:
  labels:
    group: com.stakater.platform
    provider: stakater
    version: 1.0.0    
  service:
    name: "developerhandbook"
    annotations:
      xposer.stakater.com/annotations: |-
        kubernetes.io/ingress.class: external-ingress
        ingress.kubernetes.io/force-ssl-redirect: false
        certmanager.k8s.io/cluster-issuer: letsencrypt-production
        forecastle.stakater.com/appName: Developer-Handbook
        forecastle.stakater.com/expose: true
        forecastle.stakater.com/icon: https://raw.githubusercontent.com/stakater/ForecastleIcons/master/book.png
      config.xposer.stakater.com/IngressURLTemplate: "{{ `{{.Service}}-{{.Namespace}}.{{.Domain}}` }}"
      config.xposer.stakater.com/Domain: stackator.com
      config.xposer.stakater.com/TLS: "true"
    labels:
      expose: 'true'
  deployment:
    replicas: 1
    podLabels:      
      app: developer-handbook
    containerName: handbook
    imagePullSecrets: docker-registry-secret 
    annotations:
      authproxy.stakater.com/image-name: quay.io/gambol99/keycloak-proxy
      authproxy.stakater.com/image-tag: v2.1.1
      authproxy.stakater.com/enabled: "true"
      authproxy.stakater.com/upstream-url: "http://127.0.0.1:8080"
      authproxy.stakater.com/source-service-name: developerhandbook
      authproxy.stakater.com/redirection-url: "https://developerhandbook.tools.stackator.com"
      authproxy.stakater.com/listen: "0.0.0.0:80"
    
    image:
      name: stakater/developer-handbook
      tag: 1.0.0

