apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
{{ include "developer-handbook.labels.stakater" . | indent 4 }}
{{ include "developer-handbook.labels.chart" . | indent 4 }}
  name: {{ template "developer-handbook.name" . }}
spec:
  replicas: {{ .Values.handbook.deployment.replicas }}
  template:
    metadata:
      labels:
{{ toYaml .Values.handbook.deployment.podLabels | indent 8 }}
    spec:
      imagePullSecrets:
      - name: {{ .Values.handbook.deployment.imagePullSecrets }}     
      containers:
      - name: {{ .Values.handbook.deployment.containerName }}
        image: "{{ .Values.handbook.deployment.image.name }}:{{ .Values.handbook.deployment.image.tag }}"
        ports:
        - containerPort: 8080